# Documentation: https://github.com/marketplace/actions/regex-issue-labeler
# Config .github/issue_labeler_config.yml
name: Label new issue with labeler

on:
  issues:
    types:
      - opened
      - reopened

jobs:
  label_issue:
    if: github.repository == 'martynov-alex/repository_workflows'
    uses: martynov-alex/reusable_workflows/.github/workflows/label_issue.yml@main
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
